-- Inspired from github.com/Zproger/GenesisNvim
return {
  "nvimdev/dashboard-nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    require("dashboard").setup({
      theme = "doom",
      config = {
        header = {
          "",
          "",
          "",
          "",
          "                      ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⠿⣷⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀                                             ⠀",
          "                      ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡿⠁⠀⠀⢻⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀                                             ",
          "                      ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⠁⠀⠀⠀⠀⢿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀                                              ",
          "⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣤⣤⣤⣤⣀⣀⠀⣿⡇⠀⠀⠀⠀⠀⢸⣿⡄⢀⣀⣤⣤⣤⣤⣤⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀ ⣰⣾⣷⣆ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⡇⠀⠀⠀⠀⠀⣼⣿⣿⠀⠀⣾⡿⠛⠛⠛⠛⠻⠿⢿⣿⣿⣇⡀⠀⠀⠀⢀⣠⣿⣿⣿⠿⠟⠛⠛⠛⠛⢻⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⠀⠀⠀⠀⠀⣸⣿⣿⠁⠀⠀ ⠹⢿⡿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⣸⣿⡟⢹⣿⡇⠀ ⣀⣀⣀⣿⣿⣇⣀⣀⢻⣧⣀⡀⠀⠀⠀⠀⠀⣸⣿⠛⢿⣿⣶⣾⡿⠛⢻⣿⠀⠀⠀⠀⠀⢀⣀⣸⣿⢀⣀⡀⢀⣀⣀⠀⢀⣀⣀⡀⠀⢸⣿⣿⠀⠀⠀⠀⢰⣿⣿⠃⣀⣀⣀⣀⣀⣀⡀⠀⠀⠀⠀⢀⣀⡀⢀⣀⣀⠀⢀⣀⣀⡀",
          "⠀⠀⠀⠀⣰⣿⡿⠁⢸⣿⣿⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿⣿⣧⠀⠀⠀⠀⣿⣿⣾⠿⠛⠉⠙⠿⣷⣾⣿⠀⠀⠀⠀⢰⣿⣿⣿⣷⢹⣿⡷⠿⢿⣿⣷⠿⢿⣿⣷⠀⠸⣿⣿ ⠀⠀⢠⣿⣿⠇⠀⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⣾⣿⡷⠿⢿⣿⣷⠿⢿⣿⣷",
          "⠀⠀ ⢠⣿⣿⠃⠀⠸⣿⣿⠀⠀⠀⠀⢸⣿⣿⠀⠀⠀⠘⢿⣿⣿⣯⣄⢀⣴⣾⣿⡏⠁⢀⣤⣴⣤⡀⠀⢹⣿⣷⣦⣀⢀⣼⡿⣿⡿⠋⣾⣿⠁⠀⢸⣿⡇⠀⢰⣿⣿⠀ ⣿⣿⡇⠀⠀⣾⣿⡏⠀⠀⠀⠀⠀⢸⣿⡿⠀⠀⠀⠀⢠⣿⣿⠁⠀⢸⣿⡇⠀⢰⣿⣿",
          "⠀⠀⢀⣾⣿⣏⣀⣀⣀⣿⣿ ⠀⠀⠀⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⣹⣿⣿⣏⡁⣿⡇⠀⢸⣿⣿⣿⡷⠀⢸⣿⠀⣹⣿⣿⣏⠀⠀⠀⢸⣿⣿⠀⠀⣿⣿⠁⠀⣸⣿⡏⠀⠀⣿⣿⡇⠀⣸⣿⡿⠁⠀⠀⠀⠀⠀⣾⣿⡇⠀⠀⠀⠀⢸⣿⣿⠀⠀⣿⣿⠁⠀⣸⣿⡏",
          "⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⢰⣿⣿⠇⠀⠀⠀⠀⠀⣠⣾⠟⠉⠈⠻⢿⣿⣇⡀⠈⠛⠻⠛⠁⠀⣸⣿⡿⠟⠉⠈⠻⣷⣄⠀⣼⣿⡇⠀⢠⣿⡿⠀⠀⣿⣿⠇⠀⠀⣿⣿⡇⢠⣿⣿⠁⠀⠀⠀⠀⠀⢠⣿⣿⠃⠀⠀⠀⠀⣼⣿⡇⠀⢠⣿⡿⠀⠀⣿⣿⠇",
          " ⣸⣿⣿⠁⠀⠀⠀⠀⣿⣿⡇⠀⠀⢸⣿⣿⣄⣀⣀⣀⢀⣼⡿⠃⠀⠀⠀⠀⠀⣿⣿⢿⣶⣤⣀⣤⣶⡿⢿⣿⠀⠀⠀⠀⠀⠈⢻⣷⡙⣿⠁⠀⢸⣿⡇⠀⢰⣿⣿⠀⠀⠀⢸⣿⣷⣿⣿⠃⠀⠀⣀⣀⣀⣀⣸⣿⣿⣀⣀⣀⡀⠀⣿⣿⠁⠀⢸⣿⡇⠀⢰⣿⣿⠀",
          "⢰⣿⣿⠃⠀⠀⠀⠀⠀⢿⣿⡇⠀⠀⠈⠻⢿⣿⣿⣿⡏⣾⡟⠀⠀⠀⠀⠀⠀⠀⢸⣿⣤⣼⣿⠿⢿⣷⣤⣼⡿⠀⠀⠀⠀⠀⠀⠀⢹⣿⢸⠀⠀⣿⣿⠁⠀⢸⣿⡏⠀⠀⠀⢸⣿⣿⣿⠏⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿⣿⠀⠀⣿⣿⠁⠀⢸⣿⡏⠀",
          "                     ⢿⣷⣤⣤⣤⣤⣴⣶⣾⣿⣿⡟⠃⠀⠀⠀⠘⠻⣿⣿⣿⣶⣦⣤⣤⣤⣤⣼⣿                                             ",
          "                     ⠈⠙⠛⠛⠛⠛⠛⠉⠉⠀⣿⣇⣀⠀⠀⠀⠀⢰⣿⠃⠈⠉⠛⠛⠛⠛⠛⠛⠁                                             ",
          "                     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣧⠀⠀⠀⣾⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀                                             ",
          "                     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⡏⠀⢀⣼⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀                                             ",
          "                     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣶⡾⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀                                             ",
          "",
          "",
          "",
          "",
          "",
        },
        center = {
          {
            icon = "󰈞 ",
            icon_hl = "DashboardHeader",
            desc = "Find files",
            desc_hl = "String",
            key = "m",
            key_hl = "DashboardFooter",
            action = ":Telescope find_files",
          },
          {
            icon = "󰱾 ",
            icon_hl = "DashboardHeader",
            desc = "Find recent files",
            desc_hl = "String",
            key = "n",
            key_hl = "DashboardFooter",
            action = ":Telescope oldfiles",
          },
          {
            icon = " ",
            icon_hl = "DashboardHeader",
            desc = "Find text",
            desc_hl = "String",
            key = "h",
            key_hl = "DashboardFooter",
            action = ":Telescope live_grep",
          },
          {
            icon = " ",
            icon_hl = "DashboardHeader",
            desc = "Edit config",
            desc_hl = "String",
            key = "y",
            key_hl = "DashboardFooter",
            action = ":cd $HOME/.config/nvim/ | vi init.lua",
          },
          {
            icon = " ",
            icon_hl = "DashboardHeader",
            desc = "Open Lazy",
            desc_hl = "String",
            key = "u",
            key_hl = "DashboardFooter",
            action = ":Lazy",
          },
          {
            icon = "󰏗 ",
            icon_hl = "DashboardHeader",
            desc = "Open Mason",
            desc_hl = "String",
            key = "i",
            key_hl = "DashboardFooter",
            action = ":Mason",
          },
          {
            icon = "󰩈 ",
            icon_hl = "DashboardHeader",
            desc = "Quit",
            desc_hl = "String",
            key = "q",
            key_hl = "DashboardFooter",
            action = ":q",
          },
          --[[, {
                icon = ' ',
                icon_hl = 'DashboardHeader',
                desc = 'Git Braches',
                desc_hl = 'String',
                key = 'b',
                key_hl = 'DashboardFooter',
                action = ':Telescope git_branches'
            }]]
          --
        },
      },
    })
  end,
}
